### PR TITLE
add "destroy map" button to QodotMap

### PR DESCRIPTION
**Pull request by k4gi**
hey idk if u want this but i made a "destroy map" button after i posted #110 , i think i did it right? i might have missed something

i will be looking into using materials, thanks :)

### CODE REVIEW

**Comment by DeerTears** [comment]
Does this solve your original problem of changing resource IDs on build?

Even if it does, I'm not sure if I see why this is useful compared to building an empty map file. I'd rather dedicate toolbar space to something that would automate a common problem, since there's not a lot of space in the 3D Viewport for those buttons. But I appreciate the effort, if I see someone else asking for a quick way to destroy their map I'll definitely send them to this PR.

In general Godot is bad at playing nice with git. I'm experiencing the same kind of ID update every time I change my main scene in my 2D Godot 4.x game.

**Comment by RhapsodyInGeek** [comment]
Yeah, I was going to comment earlier, I don't see anything technically wrong with the implementation but it doesn't seem particularly useful or solve any current problems. Echoing Ember, the real solution is to use the pre-existing materials system to avoid your git history issues.

Keeping this thread open for now to allow time for a response if you wanted to elaborate on why you think this proposal is necessary.

**Comment by k4gi** [comment]
yeah this destroy button "solves my problem" in the sense that i can make changes to my map, run a Full Build and test it, and then Destroy it before committing to git, avoiding the clutter of the resource IDs changing by just not keeping them

i do think it would be good if Qodot automatically created materials for the textures that you're using! but i forgot to mention before that it's not just the material IDs that are changing, but also the meshes and the collision shapes. does it make as much sense to keep copies of those? where would they go? i don't have thoughts about these things right now

a destroy button is a simple solution, to a problem that is not a big deal, just a little untidy

it is a way less important feature than the other buttons whose space it shares though!

**Comment by EMBYRDEV** [comment]
The actual solution to this problem is for us to cache generated materials in the filesystem so that multiple maps can reuse them since two map files who generate materials based on the same textures wont actually use the same material.

As for whether or not it's a useful addition in general just to clear things out again I'll leave that as an open question for now.

**Comment by yankscally** [comment]
For me it would be a welcome change, without git, it would be useful to quickly wipe the map without deleting the node. However, I'm not sure where the button is, but if it's next to 'full build' then it will also need a 'confirm map wipe?' dialogue for accidental presses. I haven't checked the PR but that would be my suggestion for something like this. 

It was something I was going to add myself as it's only a couple lines of code. Maybe 'destroy map' is not the right term, but 'wipe map'

**Pull request closed without merging**
