### PR TITLE
Fixes for godot4 rc3

### PR DESCRIPTION
**Pull request by knil79**
Fixes to make Qodot work on Godot4 rc3

### CODE REVIEW

**Comment by odecay** [comment]
Confirming that with this PR Qodot is working on release Godot 4.

**Comment by slowblink** [comment]
seconding that confirmation

**Comment by slowblink** [comment]
might actually not be working as well as I thought. I've been working on a fresh project using it and I'm encountering an error.

image

not sure what's up with this one or why I didn't see (or maybe just didn't notice) it in my other project. gonna look into it some more.

**Comment by slowblink** [comment]
image

I suppose it's all working now after a few godot restarts. getting some other errors, but I'm not sure what they're all about

**Comment by DeerTears** [comment]
Running my project on 4.0 stable with these fixes solves most errors. This is enough for RC3.

However `QuakeWadImportPlugin.cs` still has some errors on 4.0 stable, and this is the only thing (afaik) preventing the plugin from running on stable.

---

This is maybe best suited for another PR, but if someone can provide a fix for these CSharp errors that'd be great, C# is not my wheelhouse and I'm still recovering my hands. @EMBYRDEV said she'd take care of fixes, but if someone else really wants to swoop in *right now* just be sure to let all of us know explicitly that you're doing it. 

image

The errors:

```
error,C:\Users\waxwi\Desktop\Godot_v4.0-stable_mono_win64\proj\addons\qodot\src\import_plugins\QuakeWadImportPlugin.cs,81,36,CS0115,"'QuakeWadImportPlugin._GetImportOptions(string, long)': no suitable method found to override",C:\Users\waxwi\Desktop\Godot_v4.0-stable_mono_win64\proj\csharptest.csproj
error,C:\Users\waxwi\Desktop\Godot_v4.0-stable_mono_win64\proj\addons\qodot\src\import_plugins\QuakeWadImportPlugin.cs,97,23,CS0508,'QuakeWadImportPlugin._GetPresetCount()': return type must be 'int' to match overridden member 'EditorImportPlugin._GetPresetCount()',C:\Users\waxwi\Desktop\Godot_v4.0-stable_mono_win64\proj\csharptest.csproj
error,C:\Users\waxwi\Desktop\Godot_v4.0-stable_mono_win64\proj\addons\qodot\src\import_plugins\QuakeWadImportPlugin.cs,102,23,CS0508,'QuakeWadImportPlugin._GetImportOrder()': return type must be 'int' to match overridden member 'EditorImportPlugin._GetImportOrder()',C:\Users\waxwi\Desktop\Godot_v4.0-stable_mono_win64\proj\csharptest.csproj
error,C:\Users\waxwi\Desktop\Godot_v4.0-stable_mono_win64\proj\addons\qodot\src\import_plugins\QuakeWadImportPlugin.cs,107,25,CS0508,'QuakeWadImportPlugin._GetPriority()': return type must be 'float' to match overridden member 'EditorImportPlugin._GetPriority()',C:\Users\waxwi\Desktop\Godot_v4.0-stable_mono_win64\proj\csharptest.csproj
error,C:\Users\waxwi\Desktop\Godot_v4.0-stable_mono_win64\proj\addons\qodot\src\import_plugins\QuakeWadImportPlugin.cs,112,23,CS0508,"'QuakeWadImportPlugin._Import(string, string, Dictionary, Array<string>, Array<string>)': return type must be 'Error' to match overridden member 'EditorImportPlugin._Import(string, string, Dictionary, Array<string>, Array<string>)'",C:\Users\waxwi\Desktop\Godot_v4.0-stable_mono_win64\proj\csharptest.csproj
```

**Comment by knil79** [comment]
> Running my project on 4.0 stable with these fixes solves most errors. This is enough for RC3.
> 
> However `QuakeWadImportPlugin.cs` still has some errors on 4.0 stable, and this is the only thing (afaik) preventing the plugin from running on stable.
> 
> This is maybe best suited for another PR, but if someone can provide a fix for these CSharp errors that'd be great, C# is not my wheelhouse and I'm still recovering my hands. @EMBYRDEV said she'd take care of fixes, but if someone else really wants to swoop in _right now_ just be sure to let all of us know explicitly that you're doing it.
> 
> image
> 
> The errors:
> 
> ```
> error,C:\Users\waxwi\Desktop\Godot_v4.0-stable_mono_win64\proj\addons\qodot\src\import_plugins\QuakeWadImportPlugin.cs,81,36,CS0115,"'QuakeWadImportPlugin._GetImportOptions(string, long)': no suitable method found to override",C:\Users\waxwi\Desktop\Godot_v4.0-stable_mono_win64\proj\csharptest.csproj
> error,C:\Users\waxwi\Desktop\Godot_v4.0-stable_mono_win64\proj\addons\qodot\src\import_plugins\QuakeWadImportPlugin.cs,97,23,CS0508,'QuakeWadImportPlugin._GetPresetCount()': return type must be 'int' to match overridden member 'EditorImportPlugin._GetPresetCount()',C:\Users\waxwi\Desktop\Godot_v4.0-stable_mono_win64\proj\csharptest.csproj
> error,C:\Users\waxwi\Desktop\Godot_v4.0-stable_mono_win64\proj\addons\qodot\src\import_plugins\QuakeWadImportPlugin.cs,102,23,CS0508,'QuakeWadImportPlugin._GetImportOrder()': return type must be 'int' to match overridden member 'EditorImportPlugin._GetImportOrder()',C:\Users\waxwi\Desktop\Godot_v4.0-stable_mono_win64\proj\csharptest.csproj
> error,C:\Users\waxwi\Desktop\Godot_v4.0-stable_mono_win64\proj\addons\qodot\src\import_plugins\QuakeWadImportPlugin.cs,107,25,CS0508,'QuakeWadImportPlugin._GetPriority()': return type must be 'float' to match overridden member 'EditorImportPlugin._GetPriority()',C:\Users\waxwi\Desktop\Godot_v4.0-stable_mono_win64\proj\csharptest.csproj
> error,C:\Users\waxwi\Desktop\Godot_v4.0-stable_mono_win64\proj\addons\qodot\src\import_plugins\QuakeWadImportPlugin.cs,112,23,CS0508,"'QuakeWadImportPlugin._Import(string, string, Dictionary, Array<string>, Array<string>)': return type must be 'Error' to match overridden member 'EditorImportPlugin._Import(string, string, Dictionary, Array<string>, Array<string>)'",C:\Users\waxwi\Desktop\Godot_v4.0-stable_mono_win64\proj\csharptest.csproj
> ```
Theses issues are already fixed and merged to master! 
https://github.com/QodotPlugin/Qodot/blob/main/addons/qodot/src/import_plugins/QuakeWadImportPlugin.cs

you can see the difference between master and your code on row 97 for instance!

**Comment by DeerTears** [comment]
Ah thanks, the assetlib version is missing that fix. All good!

**Pull request merged**
